# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

version: "3.3"
services:
 ###############################################################################
  # Mongo
  ###############################################################################
  mongo:
    ports:
      - "$MONGO_PORT:$MONGO_PORT"
  ###############################################################################
  # NGINX
  ###############################################################################
  nginx:
    volumes:
      - ./config/nginx/etc/conf.d/dev.conf:/etc/nginx/conf.d/default.template
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      context: .
      dockerfile: pkg/authenticator/dev.Dockerfile
    volumes:
      - ./pkg/common:/usr/app/pkg/common
      - ./pkg/authenticator:/usr/app/pkg/authenticator
      - /usr/app/node_modules
      - /usr/app/pkg/authenticator/node_modules
    ports:
      - "$AUTHENTICATOR_DEBUG_PORT:9226"
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
      context: .
      dockerfile: pkg/pdfgenerator/dev.Dockerfile
    volumes:
      - ./pkg/common:/usr/app/pkg/common
      - ./pkg/pdfgenerator:/usr/app/pkg/pdfgenerator
      - /usr/app/node_modules
      - /usr/app/pkg/pdfgenerator/node_modules
    ports:
      - "$PDFGENERATOR_DEBUG_PORT:9227"
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      context: .
      dockerfile: pkg/emailer/dev.Dockerfile
    volumes:
      - ./pkg/common:/usr/app/pkg/common
      - ./pkg/emailer:/usr/app/pkg/emailer
      - /usr/app/node_modules
      - /usr/app/pkg/emailer/node_modules
    ports:
      - "$EMAILER_DEBUG_PORT:9228"
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      context: .
      dockerfile: pkg/api/dev.Dockerfile
    volumes:
      - ./pkg/common:/usr/app/pkg/common
      - ./pkg/api:/usr/app/pkg/api
      - /usr/app/node_modules
      - /usr/app/pkg/api/node_modules
    ports:
      - "$API_DEBUG_PORT:9230"
  ###############################################################################
  # Frontend
  ###############################################################################
  frontend:
    build:
      context: .
      dockerfile: pkg/landlord/dev.Dockerfile
    volumes:
      - ./pkg/common:/usr/app/pkg/common
      - ./pkg/landlord:/usr/app/pkg/landlord
      - /usr/app/pkg/landlord/public
      - /usr/app/node_modules
      - /usr/app/pkg/landlord/node_modules