# Copyright (c) 2018 Bhojpur Consulting Private Limited, India. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

version: "3.3"
services:
  ###############################################################################
  # Redis
  ###############################################################################
  # redis:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # Mongo
  ###############################################################################
  # mongo:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # NGINX
  ###############################################################################
  # nginx:
  #   logging:
  #     driver: 'syslog'
  #     options:
  #       syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
  #       tag: '{{.Name}}/{{.ID}}'
  #     #   syslog-facility: 'daemon'
  #   depends_on:
  #     - kibana
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    build:
      context: .
      dockerfile: pkg/authenticator/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    build:
      context: .
      dockerfile: pkg/pdfgenerator/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    build:
      context: .
      dockerfile: pkg/emailer/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # api
  ###############################################################################
  api:
    build:
      context: .
      dockerfile: pkg/api/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana
  ###############################################################################
  # Frontend
  ###############################################################################
  frontend:
    build:
      context: .
      dockerfile: pkg/landlord/Dockerfile
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: 'udp://localhost:$LOGSTASH_UDP_PORT'
    #     tag: '{{.Name}}/{{.ID}}'
    # depends_on:
    #   - kibana